volumes:
    op_geth_data:
    op_node_data:
    jwt_shared:
services:
    # ========================================
    # OPTIMISM NODE SERVICES
    # ========================================
    op-init:
        image: alpine:latest
        command:
            - sh
            - -c
            - |
              set -e

              # Create config directory
              mkdir -p /config

              # Generate JWT secret if it doesn't exist
              if [ ! -f '/jwt/jwt' ]; then
                echo 'Generating JWT secret'
                mkdir -p /jwt
                # Generate a 32-byte random hex string for JWT secret
                apk add --no-cache openssl
                openssl rand -hex 32 > /jwt/jwt
                chmod 666 /jwt/jwt
                echo 'JWT secret generated successfully'
              else
                echo 'JWT secret already exists, skipping generation'
              fi
        volumes:
            - op_node_data:/op-node
            - jwt_shared:/jwt
    op-geth-init:
        image: golemnetwork/golembase-l3-op-geth:v1.101511.0-0.2-holesky-test-saga8-eb0c44eb
        depends_on:
            op-init:
                condition: service_completed_successfully
        entrypoint: []
        command:
            - /bin/sh
            - -c
            - |
              set -e
              if [ ! -f '/geth/geth' ]; then
                echo 'Initializing geth data directory with genesis block...'

                # Use genesis file from op-init
                if ! geth init --state.scheme=hash --datadir='/geth' '/genesis.json'; then
                  echo 'ERROR: Failed to initialize geth with genesis block'
                  exit 1
                fi
                echo 'Geth initialized successfully with genesis block'
              else
                echo 'Geth data directory already initialized, skipping initialization'
              fi
        volumes:
            - op_geth_data:/geth
    op-geth:
        image: golemnetwork/golembase-l3-op-geth:v1.101511.0-0.2-holesky-test-saga8-eb0c44eb
        restart: unless-stopped
        stop_grace_period: 5m
        depends_on:
            op-geth-init:
                condition: service_completed_successfully
        command:
            - --networkid=42
            - --datadir=/geth
            - --http
            - --http.corsdomain=*
            - --http.vhosts=*
            - --http.addr=0.0.0.0
            - --http.port=8545
            - --http.api=admin,debug,eth,txpool,net,engine,web3,golembase,txpool
            - --ws
            - --ws.addr=0.0.0.0
            - --ws.port=8546
            - --ws.origins=*
            - --ws.api=admin,debug,eth,txpool,net,engine,web3,golembase,txpool
            - --syncmode=snap
            - --authrpc.vhosts=*
            - --authrpc.addr=0.0.0.0
            - --authrpc.port=8551
            - --authrpc.jwtsecret=/jwt/jwt
            - --usb=false
            - --state.scheme=hash
            - --nat=none
            - --bootnodes=enode://b43e8960610f0d4dcf1060c1b62aa18efdaee5616924dc9f7a069efb2d3cf063603ffccb89bb72c2c23985325fff5cc59518542850a31fef68d538e505ee8e2f@91.99.184.248:32512,enode://e9f270b3c8a2cb9f80c7fd38d368da0fda0fbbc8dcc492b2a942946a8534ca5ae19a8ce0632259841f7f354502d84fba89d921bcbfedd605df5c426336e30489@49.13.30.29:32514,enode://220310c0a900f64c5b45f3a75a08ca3a2a50f306a62bd5c7d0763fd8df8e0b3d4acbe63ce9d6eca543fab2fa73edaf95470a1a5272573e54ced5d3183b13a4b9@195.201.165.105:32516,enode://4a192d455b9599ec98a46b3e77cd774f02186d0dac63cd6fcc9008ab7de8cc73f4b9e64ef904a847ff41d3ce5b4d6a22b28b2d59e1300995712d9d43eff95fcb@91.99.157.203:32518,enode://0a413f7500673d025a96781eb450c9a94e1e42efcbf4d6330a901d7d25f54081622b03a0f79e5988115becb8b20ebcbcf6e9310efcf88c94980b6e032bed189b@91.99.94.10:32520
            - --txpool.disable.non.golembase.transactions=true
        ports:
            - 8545:8545
            - 8546:8546
        volumes:
            - op_geth_data:/geth
            - jwt_shared:/jwt
    op-node:
        image: golemnetwork/golembase-l3-op-node:v1.13.4-holesky-test-saga8-98a8cdae
        restart: unless-stopped
        stop_grace_period: 5m
        depends_on:
            op-init:
                condition: service_completed_successfully
            op-geth:
                condition: service_started
        command:
            - op-node
            - --l1=https://l2.holesky.golem-base.io/rpc
            - --l1.beacon.ignore=true
            - --l1.rpckind=standard
            - --l1.trustrpc
            - --l2=http://op-geth:8551
            - --l2.enginekind=geth
            - --l2.jwt-secret=/jwt/jwt
            - --rpc.addr=0.0.0.0
            - --rpc.port=9545
            - --p2p.nat=true
            - --p2p.ban.peers=false
            - --p2p.bootnodes=enr:-Jy4QL0b_KSsiLyylAniDtplARQ-cwJ7_U3cLtWze4SIQ6U9BAFfipSU6gkjEEZnSZWRyeN6ZeUeiDOS5bNK4rTubfCGAZl21ngrgmlkgnY0gmlwhFtjuPiHb3BzdGFja4IqAIlzZWNwMjU2azGhA0DJY696WiWYPVigXfIsqZy9FEh22DAzYSRMW54Urvc-g3RjcIJ_AYN1ZHCCfwE,enr:-Jy4QM1-dQ5O82mn-vlj1VYOU0tJCds1exAG1SWBtuaih6-MGHrlEbHKPbm105sRMIYUccV7nTXPyMh0pnmow8gz6wKGAZl21oEDgmlkgnY0gmlwhDENHh2Hb3BzdGFja4IqAIlzZWNwMjU2azGhAhUJOjZW8qa-FyHEu7q3vaWXrxvV2SbwEMZCts7V16NLg3RjcIJ_A4N1ZHCCfwM,enr:-Jy4QNwEqzbwRZ06UNpzHHc1t1yYsBU1_wwx_lE4bUZ70sgjNqyUJhrywaDsL1OKJphIaUCqRd_50hQlYpMu6OtfyuqGAZl21m60gmlkgnY0gmlwhMPJpWmHb3BzdGFja4IqAIlzZWNwMjU2azGhA8xNgKeUv6e76HK1u69ZcwZk7O8DzzsNjL0BPEa2wzI7g3RjcIJ_BYN1ZHCCfwU,enr:-Jy4QKaxjCOHgl00QtOLhvzWrzUvvL22KND1wOnQxgkQXBUWDGosMR9dRdLMmvb_Bm61ZpGoqbRqjQX6NwbJ9Wc3rmuGAZl21nZRgmlkgnY0gmlwhFtjncuHb3BzdGFja4IqAIlzZWNwMjU2azGhA_6cqqwZ1LTcsJfHveQe3ciM_QK_ilhgVQyzRRy3vMhVg3RjcIJ_B4N1ZHCCfwc,enr:-Jy4QHa-6DR20mMUqUeo5Mlj22WvGR00KCdEWHmjRCfUyMEyf4xV5E7s0_WY6q9mFN6Aj6ZWw2XaFq5qoF3sZCb6G72GAZl21ngGgmlkgnY0gmlwhFtjXgqHb3BzdGFja4IqAIlzZWNwMjU2azGhAjdYfxjp0E6gUd42dBNsKI8u9p9exHodxMVQSU3jqF3-g3RjcIJ_CYN1ZHCCfwk
            - --p2p.listen.tcp=9222
            - --p2p.listen.udp=9222
            - --metrics.enabled
            - --metrics.addr=0.0.0.0
            - --metrics.port=7300
            - --syncmode=execution-layer
            - --rollup.config=/rollup.json
            - --log.level=info
        ports:
            - 9545:9545
        volumes:
            - jwt_shared:/jwt
            - op_node_data:/op-node
