volumes:
  op_geth_data: {}
  op_node_data: {}
  jwt_shared: {}
services:
  op-init:
    image: alpine:latest
    command:
    - sh
    - -c
    - |
      set -e

      # Create config directory
      mkdir -p /config

      # Generate JWT secret if it doesn't exist
      if [ ! -f '/jwt/jwt' ]; then
        echo 'Generating JWT secret'
        mkdir -p /jwt
        # Generate a 32-byte random hex string for JWT secret
        apk add --no-cache openssl
        openssl rand -hex 32 > /jwt/jwt
        chmod 666 /jwt/jwt
        echo 'JWT secret generated successfully'
      else
        echo 'JWT secret already exists, skipping generation'
      fi
    volumes:
    - op_node_data:/op-node
    - jwt_shared:/jwt
  op-geth-init:
    image: golemnetwork/golembase-l3-op-geth:v1.101511.0-0.2-hoodi-test-lor14-2e53dae8
    depends_on:
      op-init:
        condition: service_completed_successfully
    entrypoint: []
    command:
    - /bin/sh
    - -c
    - |
      set -e
      if [ ! -f '/geth/geth' ]; then
        echo 'Initializing geth data directory with genesis block...'

        # Use genesis file from op-init
        if ! geth init --state.scheme=hash --datadir='/geth' '/genesis.json'; then
          echo 'ERROR: Failed to initialize geth with genesis block'
          exit 1
        fi
        echo 'Geth initialized successfully with genesis block'
      else
        echo 'Geth data directory already initialized, skipping initialization'
      fi
    volumes:
    - op_geth_data:/geth
  op-geth:
    image: golemnetwork/golembase-l3-op-geth:v1.101511.0-0.2-hoodi-test-lor14-2e53dae8
    restart: unless-stopped
    stop_grace_period: 5m
    depends_on:
      op-geth-init:
        condition: service_completed_successfully
    command:
    - --networkid=20032
    - --datadir=/geth
    - --http
    - --http.corsdomain=*
    - --http.vhosts=*
    - --http.addr=0.0.0.0
    - --http.port=8545
    - --http.api=admin,debug,eth,txpool,net,engine,web3,golembase,txpool
    - --ws
    - --ws.addr=0.0.0.0
    - --ws.port=8546
    - --ws.origins=*
    - --ws.api=admin,debug,eth,txpool,net,engine,web3,golembase,txpool
    - --syncmode=snap
    - --authrpc.vhosts=*
    - --authrpc.addr=0.0.0.0
    - --authrpc.port=8551
    - --authrpc.jwtsecret=/jwt/jwt
    - --usb=false
    - --state.scheme=hash
    - --nat=none
    - --bootnodes=enode://600e1dcfede211be46bc301e4fb5f65dd3de59a2729cf39b791a8b2968a60151c65338daf0007d408d23096d9fe4b157d2eafa38f4cbf8119253c231d13e97bc@195.201.165.105:30012,enode://4b6f93d785c7c0dac20bd53cccf7196ef847ed12c0f0cbf6538b9db9e85ee6ec890d639c146932751945db1d15aa83c18c6c725a32e99d3fe00498491101634e@195.201.165.105:30014,enode://458a9f24563fb03ed6511691505b1a2ed8b9a4d953a975829f422b87ba03d4d066916e6f0cf70de05f010f126ad8aab3ad9528d4d55b089a9c17f395835c2b44@195.201.165.105:30016,enode://59b99509de1252a5ad83c4404cc2e49c7d35d9c683c5567469ace8f1c4b5cc1cfb4b8b9b4b97dd354fc85a5e3a159de8c6fd11002e206d1019aaaf0cd7f9b5b3@195.201.165.105:30018,enode://e64e7dd0734a1142f9da8d6c801abfc83391f42cd5ad5409c5edf419d274105f478f04d25e2379a0244ba45d9cca4a2ba1ef8e3c710a82d31b99dcb84167ca06@195.201.165.105:30020
    - --txpool.disable.non.golembase.transactions=true
    ports:
    - 8545:8545
    - 8546:8546
    volumes:
    - op_geth_data:/geth
    - jwt_shared:/jwt
  op-node:
    image: golemnetwork/golembase-l3-op-node:v1.13.4-hoodi-test-lor14-42edafbd
    restart: unless-stopped
    stop_grace_period: 5m
    depends_on:
      op-init:
        condition: service_completed_successfully
      op-geth:
        condition: service_started
    command:
    - op-node
    - --l1=https://l2.holesky.golem-base.io/rpc
    - --l1.beacon.ignore=true
    - --l1.rpckind=standard
    - --l1.trustrpc
    - --l2=http://op-geth:8551
    - --l2.enginekind=geth
    - --l2.jwt-secret=/jwt/jwt
    - --rpc.addr=0.0.0.0
    - --rpc.port=9545
    - --p2p.nat=true
    - --p2p.ban.peers=false
    - --p2p.bootnodes=enr:-J64QJUxeO4YH_lomj7-9Re4wQ63eZBX6JkqojQTTgaPRO9hYjKMMoC8JIxQlconUaBS0okKcDWDoIuR5jSsThJ_FtWGAZnJL1b7gmlkgnY0gmlwhMPJpWmHb3BzdGFja4TAnAEAiXNlY3AyNTZrMaECTiTTtpyLlxE7gewIc8CdaSepN8koasFiExO4HDn3h7SDdGNwgnU9g3VkcIJ1PQ,enr:-J64QJrh8d87wRLGAvLh_okVfX22MUe7ThroXkIJmhuZR58kLxVHbESzhUd7cBGauoeLkH88hOjKyUXn92eoucouk9aGAZnJL1fMgmlkgnY0gmlwhMPJpWmHb3BzdGFja4TAnAEAiXNlY3AyNTZrMaEDRKV3bJh-JpPtB5D2BhTnshuueGxAZtWwyDx1O7i4ZkiDdGNwgnU_g3VkcIJ1Pw,enr:-J64QOSBKXCfqpX7WWaT68_pfdeF9LVYpIX9VD9H-JNGISXrCUTYdldY9DbpcPZ_Tech_Ylr1V9d-6qtcgpEz6Y5rzWGAZnJL1fNgmlkgnY0gmlwhMPJpWmHb3BzdGFja4TAnAEAiXNlY3AyNTZrMaECoNWOG8EIkJZZTiWf9yZQ8nQINPTBGewGnkunVrCZokmDdGNwgnVBg3VkcIJ1QQ,enr:-J64QPNCcJjXeT7jlzflAJEF4dey7Myk9EolDOOeF-Zy3PbcIwGBE-jQYPJ8cKxH0HbqR8I8PZjwisT5MYRETQe31IeGAZnJL1evgmlkgnY0gmlwhMPJpWmHb3BzdGFja4TAnAEAiXNlY3AyNTZrMaEDIAQ-LDH2a5Yrcfe-ic08JU8O0zfRXRM2w7u4rAeeWvSDdGNwgnVDg3VkcIJ1Qw,enr:-J64QIm-4FNY0DuUt2nxRQSdq1xK6gGTBI7pRtPmQpomE5bFE4OLmuI-AqNtBSES5QS0JvqWVH3cK7XjcD5U7PhP6hSGAZnJL1cagmlkgnY0gmlwhMPJpWmHb3BzdGFja4TAnAEAiXNlY3AyNTZrMaECgNaLegh9FzDRs6U7owSxGe8pfkjBOfe-iYXhMUGHSyuDdGNwgnVFg3VkcIJ1RQ
    - --p2p.listen.tcp=9222
    - --p2p.listen.udp=9222
    - --metrics.enabled
    - --metrics.addr=0.0.0.0
    - --metrics.port=7300
    - --syncmode=execution-layer
    - --rollup.config=/rollup.json
    - --log.level=info
    ports:
    - 9545:9545
    volumes:
    - jwt_shared:/jwt
    - op_node_data:/op-node
