volumes:
    op_geth_data:
    op_node_data:
    jwt_shared:
services:
    # ========================================
    # OPTIMISM NODE SERVICES
    # ========================================
    op-init:
        image: alpine:latest
        command:
            - sh
            - -c
            - |
              set -e

              # Create config directory
              mkdir -p /config

              # Generate JWT secret if it doesn't exist
              if [ ! -f '/jwt/jwt' ]; then
                echo 'Generating JWT secret'
                mkdir -p /jwt
                # Generate a 32-byte random hex string for JWT secret
                apk add --no-cache openssl
                openssl rand -hex 32 > /jwt/jwt
                chmod 666 /jwt/jwt
                echo 'JWT secret generated successfully'
              else
                echo 'JWT secret already exists, skipping generation'
              fi
        volumes:
            - op_node_data:/op-node
            - jwt_shared:/jwt
    op-geth-init:
        image: golemnetwork/golembase-l3-op-geth:snapsync-holesky-ramses-c88c6447
        depends_on:
            op-init:
                condition: service_completed_successfully
        entrypoint: []
        command:
            - /bin/sh
            - -c
            - |
              set -e
              if [ ! -f '/geth/geth' ]; then
                echo 'Initializing geth data directory with genesis block...'

                # Use genesis file from op-init
                if ! geth init --state.scheme=hash --datadir='/geth' '/genesis.json'; then
                  echo 'ERROR: Failed to initialize geth with genesis block'
                  exit 1
                fi
                echo 'Geth initialized successfully with genesis block'
              else
                echo 'Geth data directory already initialized, skipping initialization'
              fi
        volumes:
            - op_geth_data:/geth
    op-geth:
        image: golemnetwork/golembase-l3-op-geth:snapsync-holesky-ramses-c88c6447
        restart: unless-stopped
        stop_grace_period: 5m
        depends_on:
            op-geth-init:
                condition: service_completed_successfully
        command:
            - --networkid=60138453035
            - --datadir=/geth
            - --http
            - --http.corsdomain=*
            - --http.vhosts=*
            - --http.addr=0.0.0.0
            - --http.port=8545
            - --http.api=admin,debug,eth,txpool,net,engine,web3,golembase,txpool
            - --ws
            - --ws.addr=0.0.0.0
            - --ws.port=8546
            - --ws.origins=*
            - --ws.api=admin,debug,eth,txpool,net,engine,web3,golembase,txpool
            - --syncmode=snap
            - --authrpc.vhosts=*
            - --authrpc.addr=0.0.0.0
            - --authrpc.port=8551
            - --authrpc.jwtsecret=/jwt/jwt
            - --usb=false
            - --state.scheme=hash
            - --nat=none
            - --bootnodes=enode://b03bfbd8bf0c5fcda643d49cee717086e418ae89258b76c4be2950d3fb0dfc3dc7380dc037459b80aa8c0d3f9655d8ed84f9199706f557cfbde203cb6230fecb@142.132.206.248:46012,enode://c7183bc09c7ddb4b17355d1f25da295f70c0fa88bbb6ac78839a318f959c5585a8e107934baad78f729cb0cab4e286f312eca33a6c08e08a19409c570fc48e83@142.132.206.232:46014,enode://f72d0799fa690c24c3a1ddbcd98d148dd41472253006712eaeeb6e7d908763efd186e935d2892ee6769c9f7aef1c94741174ba7402b5feb4c99b20aa3257bcb3@142.132.206.248:46016,enode://79c8d72d31330885f977544d69f0661cc5df0652979d3e71cf0a9b8ff03ca666ca466871391c6d2abf8baad00dfe61d95b5090eff26a4fc05e9625ec0dec6478@142.132.206.232:46018,enode://f97c3eb8b3023a66642be248160726beb9ec1bbd6bbbaca822c8bf02dcfed5148a6603447018a9c3641fb9b81229602b05a37317f8b31872611727787c51e114@37.27.230.18:46020
            - --txpool.disable.non.golembase.transactions=true
        ports:
            - 8545:8545
            - 8546:8546
        volumes:
            - op_geth_data:/geth
            - jwt_shared:/jwt
    op-node:
        image: golemnetwork/golembase-l3-op-node:v1.13.5-holesky-ramses-e9e435e0
        restart: unless-stopped
        stop_grace_period: 5m
        depends_on:
            op-init:
                condition: service_completed_successfully
            op-geth:
                condition: service_started
        command:
            - op-node
            - --l1=https://l2.holesky.golem-base.io/rpc
            - --l1.beacon.ignore=true
            - --l1.rpckind=standard
            - --l1.trustrpc
            - --l2=http://op-geth:8551
            - --l2.enginekind=geth
            - --l2.jwt-secret=/jwt/jwt
            - --rpc.addr=0.0.0.0
            - --rpc.port=9545
            - --p2p.nat=true
            - --p2p.ban.peers=false
            - --p2p.bootnodes=enr:-KG4QDzmzxrOtTQHCqqjlnqVi8nXYj4a-yPZ99g3SWWLmICiCFfviUcynSC6mYCIZDPIeu9aB8PQJoQffc-6DRVnP-iGAZlYCAJpgmlkgnY0gmlwhI6EzviHb3BzdGFja4er8J-E4AEAiXNlY3AyNTZrMaEDT2hSRn7mLglumm_2kQbft03ZnE7ievmUt8KRycZHdviDdGNwgrO9g3VkcIKzvQ,enr:-KG4QCshPDauBI4NN0pKvIDx4M4uvC65L9qLWkDnuAjYUREEOpxnLXIME0yFwqNJWqoo4hBSRnv1X8bDHU5LXxjIhySGAZlYB__egmlkgnY0gmlwhI6EzuiHb3BzdGFja4er8J-E4AEAiXNlY3AyNTZrMaEC2mEnfNgi1B5dpxV-gOQKZyvGbYzD4LFupyJY0m_BUYiDdGNwgrO_g3VkcIKzvw,enr:-KG4QJWsh-hT2izRGIa9a8_k0_8Gw4LtjrTtHU4Rd2I7reKPL4t0wgKKXT5YG9Wimz4ZCMGfD3dAD6oWjaS_ZaCjW4SGAZlYCAY8gmlkgnY0gmlwhI6EzviHb3BzdGFja4er8J-E4AEAiXNlY3AyNTZrMaECLZNnLAdBuoEXEBAdzy5F7umRtanO5M-RfwfrDLvTFvODdGNwgrPBg3VkcIKzwQ,enr:-KG4QP0gQ9VRyEUxMGhBNvg1K9upWFu14WiHyG3J-EXUi4TGXqjTqIsuAmMsbGxhh7x5aVzqjIPF9VwZuVhMdpcG0laGAZlYCAfLgmlkgnY0gmlwhI6EzuiHb3BzdGFja4er8J-E4AEAiXNlY3AyNTZrMaEDHJLiw2rQZxRtNzm0OqGyLh6d9Q-2Dl5W1IuXytIrAbyDdGNwgrPDg3VkcIKzww,enr:-KG4QOVBlHiLSvFAXh10GucEuiRHdnCFsVsxzFzi2Vp7gduKLjIl7QoBHEN_zYCk8kndrOrZiwb2b9uZ4QbafP_sAgOGAZlYCK_8gmlkgnY0gmlwhCUb5hKHb3BzdGFja4er8J-E4AEAiXNlY3AyNTZrMaEDl3KuYSGs-MeO1myN7O1sH_yBmqgjcoJ12Zy2qerYd5eDdGNwgrPFg3VkcIKzxQ
            - --p2p.listen.tcp=9222
            - --p2p.listen.udp=9222
            - --metrics.enabled
            - --metrics.addr=0.0.0.0
            - --metrics.port=7300
            - --syncmode=execution-layer
            - --rollup.config=/rollup.json
            - --log.level=info
        ports:
            - 9545:9545
        volumes:
            - jwt_shared:/jwt
            - op_node_data:/op-node
