volumes:
    op_geth_data:
    op_node_data:
    jwt_shared:
services:
    # ========================================
    # OPTIMISM NODE SERVICES
    # ========================================
    op-init:
        image: alpine:latest
        command:
            - sh
            - -c
            - |
              set -e

              # Create config directory
              mkdir -p /config

              # Generate JWT secret if it doesn't exist
              if [ ! -f '/jwt/jwt' ]; then
                echo 'Generating JWT secret'
                mkdir -p /jwt
                # Generate a 32-byte random hex string for JWT secret
                apk add --no-cache openssl
                openssl rand -hex 32 > /jwt/jwt
                chmod 666 /jwt/jwt
                echo 'JWT secret generated successfully'
              else
                echo 'JWT secret already exists, skipping generation'
              fi
        volumes:
            - op_node_data:/op-node
            - jwt_shared:/jwt
    op-geth-init:
        image: golemnetwork/golembase-l3-op-geth:v1.101511.0-0.2-holesky-testqjnk-7a66e011
        depends_on:
            op-init:
                condition: service_completed_successfully
        entrypoint: []
        command:
            - /bin/sh
            - -c
            - |
              set -e
              if [ ! -f '/geth/geth' ]; then
                echo 'Initializing geth data directory with genesis block...'

                # Use genesis file from op-init
                if ! geth init --state.scheme=hash --datadir='/geth' '/genesis.json'; then
                  echo 'ERROR: Failed to initialize geth with genesis block'
                  exit 1
                fi
                echo 'Geth initialized successfully with genesis block'
              else
                echo 'Geth data directory already initialized, skipping initialization'
              fi
        volumes:
            - op_geth_data:/geth
    op-geth:
        image: golemnetwork/golembase-l3-op-geth:v1.101511.0-0.2-holesky-testqjnk-7a66e011
        restart: unless-stopped
        stop_grace_period: 5m
        depends_on:
            op-geth-init:
                condition: service_completed_successfully
        command:
            - --networkid=11
            - --datadir=/geth
            - --http
            - --http.corsdomain=*
            - --http.vhosts=*
            - --http.addr=0.0.0.0
            - --http.port=8545
            - --http.api=admin,debug,eth,txpool,net,engine,web3,golembase,txpool
            - --ws
            - --ws.addr=0.0.0.0
            - --ws.port=8546
            - --ws.origins=*
            - --ws.api=admin,debug,eth,txpool,net,engine,web3,golembase,txpool
            - --syncmode=snap
            - --authrpc.vhosts=*
            - --authrpc.addr=0.0.0.0
            - --authrpc.port=8551
            - --authrpc.jwtsecret=/jwt/jwt
            - --usb=false
            - --state.scheme=hash
            - --nat=none
            - --bootnodes=enode://71ad19c61643c0532daf18d41335eb7871c50965def82e931ee7ac0652b25dd051f21c75e5664ddd900911c7dff7645b248d3f62a428840ee5073a55da9b1d57@91.99.184.248:32512,enode://c26992835f8a6eaa5ab615b8af25c2f9fcc86c25aa6b164abd1b2c772071bdbe7e56ce8b2131bf890a2e9acb9f2cdb1fd290224f61a0f1295b808197af4c9f17@195.201.165.105:32514,enode://e5c04f382b1002219f6dd340c3b31d5f4c78be8d492cccc18e08f779b1712018a5cceabb656fb1b77e673b04fb98d7f1bdfe28c76f1c35234fb320a1434f33fb@195.201.165.105:32516,enode://c49433a7fa90fce34f4ab88c4f0c0783fb57edcb55274d98af1f6c9a39d0f50683365bf43575d05a6f5588e2471c47846846c1a1f0feaf784ddda1142e115c9d@91.99.157.203:32518,enode://cabbcfe88d318d4daa90bedd0cab36bbba1f01bb8326931463bf6d3a8d4416d1515930f3e6622a145941fedb69e30dabb824880a940c5f9894ef2b1bc657a687@195.201.165.105:32520
            - --txpool.disable.non.golembase.transactions=true
        ports:
            - 8545:8545
            - 8546:8546
        volumes:
            - op_geth_data:/geth
            - jwt_shared:/jwt
    op-node:
        image: golemnetwork/golembase-l3-op-node:v1.13.4-holesky-testqjnk-e960531d
        restart: unless-stopped
        stop_grace_period: 5m
        depends_on:
            op-init:
                condition: service_completed_successfully
            op-geth:
                condition: service_started
        command:
            - op-node
            - --l1=https://l2.holesky.golem-base.io/rpc
            - --l1.beacon.ignore=true
            - --l1.rpckind=standard
            - --l1.trustrpc
            - --l2=http://op-geth:8551
            - --l2.enginekind=geth
            - --l2.jwt-secret=/jwt/jwt
            - --rpc.addr=0.0.0.0
            - --rpc.port=9545
            - --p2p.nat=true
            - --p2p.ban.peers=false
            - --p2p.bootnodes=enr:-Jy4QCzm14CL-n5vsmGF5g-avKnwBnIs929RDsrxEnoyjSOmIrR76Nq09iv0zdIpoIJ_9MSJeoaAdKFzHYsS0f28v2eGAZlcCAIQgmlkgnY0gmlwhFtjuPiHb3BzdGFja4ILAIlzZWNwMjU2azGhArxhXF2dzuWyouh6sIm-V923m0RL9rOnv2ZilSYA4G8dg3RjcIJ_AYN1ZHCCfwE,enr:-Jy4QAlXIlq9nfniYQQQ6P3WJKRJxgHocULutZMFAOr2cG0WRgXIDcpUq2JjBdq37oI2Bg4aXnwBJC4hk_KnQ_hfbemGAZlUMwVwgmlkgnY0gmlwhMPJpWmHb3BzdGFja4ILAIlzZWNwMjU2azGhAk5wDBMv9WtXuMuMNDLPhkMWC8mPjyinIRIPlcMpre-Xg3RjcIJ_A4N1ZHCCfwM,enr:-Jy4QJEGcRGz4jftGaSNaCffU3VVk9_szrDbynrAZzgvspP2ei2Fopfdpz_LKW6yYrwRexXIPbpL0eBuqnCvUGiF-ECGAZlUMxFYgmlkgnY0gmlwhMPJpWmHb3BzdGFja4ILAIlzZWNwMjU2azGhAx5t5VBwY8jdvHQK75Nx-ncyk4GCuin0ARcobpVOTjIig3RjcIJ_BYN1ZHCCfwU,enr:-Jy4QG2EoFG-mCI50ZBGH3pCyWEcit1LbC6oumqYy3saQ4ZTcKHv4-KP4HahbB8nvvVxgaeBIvRwUANDSd2QOAIruuWGAZlW41cSgmlkgnY0gmlwhFtjncuHb3BzdGFja4ILAIlzZWNwMjU2azGhA_lkJRmdjJt3HAG7Oftirxbh29AYn3QhhcKzneqbUFxug3RjcIJ_B4N1ZHCCfwc,enr:-Jy4QAv2qh0hv1NDUGruasY4Oi4qCAekRGgFNefovAtw0xkXawXv9OSrP3V565GedUEcUVyR1Amt6Uj_wykCYVK5Yw2GAZlUMxFLgmlkgnY0gmlwhMPJpWmHb3BzdGFja4ILAIlzZWNwMjU2azGhAhz4kP-61NLBHMEu3_ttzlHNybLA-zlRJP_nSWRd2SgYg3RjcIJ_CYN1ZHCCfwk
            - --p2p.listen.tcp=9222
            - --p2p.listen.udp=9222
            - --metrics.enabled
            - --metrics.addr=0.0.0.0
            - --metrics.port=7300
            - --syncmode=execution-layer
            - --rollup.config=/rollup.json
            - --log.level=info
        ports:
            - 9545:9545
        volumes:
            - jwt_shared:/jwt
            - op_node_data:/op-node
