volumes:
  op_geth_data:
  op_node_data:
  jwt_shared:

services:
  # ========================================
  # OPTIMISM NODE SERVICES
  # ========================================
  op-init:
    image: alpine:latest
    command:
      - sh
      - -c
      - |
        set -e

        # Create config directory
        mkdir -p /config

        # Generate JWT secret if it doesn't exist
        if [ ! -f '/jwt/jwt' ]; then
          echo 'Generating JWT secret'
          mkdir -p /jwt
          # Generate a 32-byte random hex string for JWT secret
          apk add --no-cache openssl
          openssl rand -hex 32 > /jwt/jwt
          chmod 666 /jwt/jwt
          echo 'JWT secret generated successfully'
        else
          echo 'JWT secret already exists, skipping generation'
        fi
    volumes:
      - op_node_data:/op-node
      - jwt_shared:/jwt

  op-geth-init:
    image: golemnetwork/golembase-l3-op-geth:v1.101511.0-0.1-kaolin-0c3aa967
    depends_on:
      op-init:
        condition: service_completed_successfully
    entrypoint: []
    command:
      - /bin/sh
      - -c
      - |
        set -e
        if [ ! -f '/geth/geth' ]; then
          echo 'Initializing geth data directory with genesis block...'

          # Use genesis file from op-init
          if ! geth init --state.scheme=hash --datadir='/geth' '/genesis.json'; then
            echo 'ERROR: Failed to initialize geth with genesis block'
            exit 1
          fi
          echo 'Geth initialized successfully with genesis block'
        else
          echo 'Geth data directory already initialized, skipping initialization'
        fi
    volumes:
      - op_geth_data:/geth

  op-geth:
    image: golemnetwork/golembase-l3-op-geth:v1.101511.0-0.1-kaolin-0c3aa967
    restart: unless-stopped
    stop_grace_period: 5m
    depends_on:
      op-geth-init:
        condition: service_completed_successfully
    command:
      - --networkid=600606
      - --datadir=/geth
      - --http
      - --http.corsdomain=*
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=debug,eth,txpool,net,engine,web3,golembase,txpool
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.origins=*
      - --ws.api=debug,eth,txpool,net,engine,web3,golembase,txpool
      - --syncmode=snap
      - --authrpc.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.jwtsecret=/jwt/jwt
      - --usb=false
      - --state.scheme=hash
      - --nat=none
      - --bootnodes=enode://e2cd54c559031fd9c2119f7b5f78663e2fea93a0d7d11e54549bae6477557f9d1711e221ba934b89cd9264323849c8d183ba8c0d17202239e51e6152210f0bba@37.27.230.18:31800,enode://3f15bd20a4a58bd1e9e6801f7e0d9a689ec84f47edfccd119a960735c7c763a386dca04a63767a66248baace84858a2f87b0ae234c5d3d1fb497626bba05a20f@116.202.192.224:31802,enode://24952b80e017746f31bb8c269fe02346c7d1b66a277ab84cb9823f0fb228e13685ad9f0913a6aa978bc23104294feb3ad638c4a89588df9713da36ae8a0667e4@116.202.192.224:31804
      - --txpool.disable.non.golembase.transactions=true
    ports:
      - 8545:8545
      - 8546:8546
    volumes:
      - op_geth_data:/geth
      - jwt_shared:/jwt

  op-node:
    image: golemnetwork/golembase-l3-op-node:v1.13.0-kaolin-d03a3526
    restart: unless-stopped
    stop_grace_period: 5m
    depends_on:
      op-init:
        condition: service_completed_successfully
      op-geth:
        condition: service_started
    command:
      - op-node
      - --l1=https://rpc.l2.holesky.golem-base.io
      - --l1.beacon.ignore=true
      - --l1.rpckind=standard
      - --l1.trustrpc
      - --l2=http://op-geth:8551
      - --l2.enginekind=geth
      - --l2.jwt-secret=/jwt/jwt
      - --rpc.addr=0.0.0.0
      - --rpc.port=9545
      - --p2p.nat=true
      - --p2p.ban.peers=false
      - --p2p.bootnodes=enr:-J64QOUWjl7nYDyHzZ9UoeATrlEQrIBj5Jbpa2y3q4quB1snUxejQXOx7B_sHpTtCgkkBQn_gKs1Yq9kzhCt8IBKDL6GAZdFIGM_gmlkgnY0gmlwhCUb5hKHb3BzdGFja4Se1CQAiXNlY3AyNTZrMaEDWsVcq4QYNyJtBF8nY2Z4R3H9c1eT8EC9rwC1el-oXYeDdGNwgnw5g3VkcIJ8OQ,enr:-J64QEMwleVcc6j0qvGWhjVTQqAw0MHy7KAcQNck0OW8iknpdRGvmJQ5xuzb75zPmNSpTHLuP-zjk4-la4GJrHlg5zKGAZdFIEE0gmlkgnY0gmlwhHTKwOCHb3BzdGFja4Se1CQAiXNlY3AyNTZrMaEC1LpCoSVYFpmKsH3zLFiDG2dOLHFYluxKVX0OLyFI3jKDdGNwgnw7g3VkcIJ8Ow,enr:-J64QKlHXDmvJjQV1YBXLFeXf6oNKynMYhRvHdT-ZC8vvnKoPijr_jwFJT32yw4WfWJuvXwfzMv-IKc4DBXiBJ-SIu6GAZdFID1kgmlkgnY0gmlwhHTKwOCHb3BzdGFja4Se1CQAiXNlY3AyNTZrMaEDMTI-N9CPqGBchy7Ep34p1ssTmxMmjFHPScScVMA5shSDdGNwgnw9g3VkcIJ8PQ
      - --p2p.listen.tcp=9222
      - --p2p.listen.udp=9222
      - --metrics.enabled
      - --metrics.addr=0.0.0.0
      - --metrics.port=7300
      - --syncmode=execution-layer
      - --rollup.config=/rollup.json
      - --log.level=info
    ports:
      - 9545:9545
    volumes:
      - jwt_shared:/jwt
      - op_node_data:/op-node
