volumes:
    op_geth_data:
    op_node_data:
    jwt_shared:
services:
    # ========================================
    # OPTIMISM NODE SERVICES
    # ========================================
    op-init:
        image: alpine:latest
        command:
            - sh
            - -c
            - |
              set -e

              # Create config directory
              mkdir -p /config

              # Generate JWT secret if it doesn't exist
              if [ ! -f '/jwt/jwt' ]; then
                echo 'Generating JWT secret'
                mkdir -p /jwt
                # Generate a 32-byte random hex string for JWT secret
                apk add --no-cache openssl
                openssl rand -hex 32 > /jwt/jwt
                chmod 666 /jwt/jwt
                echo 'JWT secret generated successfully'
              else
                echo 'JWT secret already exists, skipping generation'
              fi
        volumes:
            - op_node_data:/op-node
            - jwt_shared:/jwt
    op-geth-init:
        image: golemnetwork/golembase-l3-op-geth:v1.101511.0-1.5-holesky-ethwarsaw-f4dd8e0f
        depends_on:
            op-init:
                condition: service_completed_successfully
        entrypoint: []
        command:
            - /bin/sh
            - -c
            - |
              set -e
              if [ ! -f '/geth/geth' ]; then
                echo 'Initializing geth data directory with genesis block...'

                # Use genesis file from op-init
                if ! geth init --state.scheme=hash --datadir='/geth' '/genesis.json'; then
                  echo 'ERROR: Failed to initialize geth with genesis block'
                  exit 1
                fi
                echo 'Geth initialized successfully with genesis block'
              else
                echo 'Geth data directory already initialized, skipping initialization'
              fi
        volumes:
            - op_geth_data:/geth
    op-geth:
        image: golemnetwork/golembase-l3-op-geth:v1.101511.0-1.5-holesky-ethwarsaw-f4dd8e0f
        restart: unless-stopped
        stop_grace_period: 5m
        depends_on:
            op-geth-init:
                condition: service_completed_successfully
        command:
            - --networkid=60138453033
            - --datadir=/geth
            - --http
            - --http.corsdomain=*
            - --http.vhosts=*
            - --http.addr=0.0.0.0
            - --http.port=8545
            - --http.api=admin,debug,eth,txpool,net,engine,web3,golembase,txpool
            - --ws
            - --ws.addr=0.0.0.0
            - --ws.port=8546
            - --ws.origins=*
            - --ws.api=admin,debug,eth,txpool,net,engine,web3,golembase,txpool
            - --syncmode=snap
            - --authrpc.vhosts=*
            - --authrpc.addr=0.0.0.0
            - --authrpc.port=8551
            - --authrpc.jwtsecret=/jwt/jwt
            - --usb=false
            - --state.scheme=hash
            - --nat=none
            - --bootnodes=enode://deed7770dd9da35d95a5d07ba5eaad2a8b0da0ed70980710b82620be34cc000979591e4669971984bc5f04554ee00a264afa88e889d2e739f661c85f7fd441b2@142.132.206.232:46024,enode://cd6411d94228d0dd2d5e0e88c71cc088fc5f6d59a102fa5dfc0357d4f658a09d165d3ec8d73fb576191bc12c055c8943a03092902031b4dec5ff72f2de36e432@78.46.85.197:46026,enode://f9984550d5eb6a94f9855826f26af1583db818dd1bceda911cd6c5d3067748ac4abf514651840b56e7e25d40cba6bf32d3d08a719c95926d12b45543b56ab4ce@116.202.192.224:46028,enode://3f9aaf055c4afc43404077cf66b5506e01f440724a6f5c7e4e043bc984007577c04ab12b63c263f2eefeebb670e8c4d526978acdfb8d0ca63c1109c0fb49b79f@5.9.17.176:46030,enode://fca486047c7eb00c54b98daf697a2500c6f6380468fe1a000d96428b7b7f7074a101971e290eba24e71c1a58a235e32cfa0af247353e78293d61dbf0795be92e@116.202.193.109:46032
            - --txpool.disable.non.golembase.transactions=true
        ports:
            - 8545:8545
            - 8546:8546
        volumes:
            - op_geth_data:/geth
            - jwt_shared:/jwt
    op-node:
        image: golemnetwork/golembase-l3-op-node:v1.13.5-holesky-ethwarsaw-98131e2e
        restart: unless-stopped
        stop_grace_period: 5m
        depends_on:
            op-init:
                condition: service_completed_successfully
            op-geth:
                condition: service_started
        command:
            - op-node
            - --l1=https://l2.holesky.golem-base.io/rpc
            - --l1.beacon.ignore=true
            - --l1.rpckind=standard
            - --l1.trustrpc
            - --l2=http://op-geth:8551
            - --l2.enginekind=geth
            - --l2.jwt-secret=/jwt/jwt
            - --rpc.addr=0.0.0.0
            - --rpc.port=9545
            - --p2p.nat=true
            - --p2p.ban.peers=false
            - --p2p.bootnodes=enr:-KG4QHVFusfXMg_to6vZtDN2-hWQ7Ha16A7v7gsZ5XKKjLZOeu80-YQ9WJgx7rbkPHinf81Wl1ttN69olhBdWQXRTTOGAZkXEB3KgmlkgnY0gmlwhI6EzuiHb3BzdGFja4ep8J-E4AEAiXNlY3AyNTZrMaEClBG3UTk3PqY0OxgvV-JTdkPqUeiPg3tz6r0zBEfp99GDdGNwgrPJg3VkcIKzyQ,enr:-KG4QLV362F3KJTeo8MU4DiFH7jz9WlZagl6DIKHEkx1lSX3ZFuNhJvTdbPrVWDazfet2XGFdcM5YHeRbMRRoxn8NlOGAZkXEDO2gmlkgnY0gmlwhE4uVcWHb3BzdGFja4ep8J-E4AEAiXNlY3AyNTZrMaEC2-T4Sm-VrTzMuLMj2TOWQdqLJWkWLGOipH4Fqp98qFyDdGNwgrPLg3VkcIKzyw,enr:-KG4QAm5FJXeVoaNcdn6fN2rMGhxAKjprUVgHzF2Jp2zGUY2LxXs-GluVs9S26pPaGZAnp5DKFZ1tLOZgCYshMdxiSeGAZkXECbmgmlkgnY0gmlwhHTKwOCHb3BzdGFja4ep8J-E4AEAiXNlY3AyNTZrMaEDxXT59s4DE-yJTt9_iSf9i2wFiztR94K9jNl3Lk3-HHaDdGNwgrPNg3VkcIKzzQ,enr:-KG4QGJquMqX2YOX87xr3P1Kuim9K_QrdXDFnDsEgjIaXEk0FVIbURHD3rDyVwv2yL5YOp3B-VtyCGG23GTtw_CMeFSGAZkXEDyugmlkgnY0gmlwhAUJEbCHb3BzdGFja4ep8J-E4AEAiXNlY3AyNTZrMaECsJ2X8T0FdN6Tj2aHJYPwICELmwo9uw27Nl6_Nuhh5sWDdGNwgrPPg3VkcIKzzw,enr:-KG4QFVoRC0mjD-w_o2OPv1GFeOuFGeVi3goqlNjPJZLKXI1DxE9Mw1fgzZg-VD5tQS8QeuwTca5L5ZnomvF6ESDZp-GAZkXEB9qgmlkgnY0gmlwhHTKwW2Hb3BzdGFja4ep8J-E4AEAiXNlY3AyNTZrMaECSY4NZg5eHuNaj89KQSaHnH7J-wdKp3yjgOMtgzxo-vyDdGNwgrPRg3VkcIKz0Q
            - --p2p.listen.tcp=9222
            - --p2p.listen.udp=9222
            - --metrics.enabled
            - --metrics.addr=0.0.0.0
            - --metrics.port=7300
            - --syncmode=execution-layer
            - --rollup.config=/rollup.json
            - --log.level=info
        ports:
            - 9545:9545
        volumes:
            - jwt_shared:/jwt
            - op_node_data:/op-node
