volumes:
  op_geth_data: {}
  op_node_data: {}
  jwt_shared: {}
services:
  op-init:
    image: alpine:latest
    command:
    - sh
    - -c
    - |
      set -e

      # Create config directory
      mkdir -p /config

      # Generate JWT secret if it doesn't exist
      if [ ! -f '/jwt/jwt' ]; then
        echo 'Generating JWT secret'
        mkdir -p /jwt
        # Generate a 32-byte random hex string for JWT secret
        apk add --no-cache openssl
        openssl rand -hex 32 > /jwt/jwt
        chmod 666 /jwt/jwt
        echo 'JWT secret generated successfully'
      else
        echo 'JWT secret already exists, skipping generation'
      fi
    volumes:
    - op_node_data:/op-node
    - jwt_shared:/jwt
  op-geth-init:
    image: golemnetwork/golembase-l3-op-geth:v1.101511.0-0.2-holesky-t4-491d1849
    depends_on:
      op-init:
        condition: service_completed_successfully
    entrypoint: []
    command:
    - /bin/sh
    - -c
    - |
      set -e
      if [ ! -f '/geth/geth' ]; then
        echo 'Initializing geth data directory with genesis block...'

        # Use genesis file from op-init
        if ! geth init --state.scheme=hash --datadir='/geth' '/genesis.json'; then
          echo 'ERROR: Failed to initialize geth with genesis block'
          exit 1
        fi
        echo 'Geth initialized successfully with genesis block'
      else
        echo 'Geth data directory already initialized, skipping initialization'
      fi
    volumes:
    - op_geth_data:/geth
  op-geth:
    image: golemnetwork/golembase-l3-op-geth:v1.101511.0-0.2-holesky-t4-491d1849
    restart: unless-stopped
    stop_grace_period: 5m
    depends_on:
      op-geth-init:
        condition: service_completed_successfully
    command:
    - --networkid=20003
    - --datadir=/geth
    - --http
    - --http.corsdomain=*
    - --http.vhosts=*
    - --http.addr=0.0.0.0
    - --http.port=8545
    - --http.api=admin,debug,eth,txpool,net,engine,web3,golembase,txpool
    - --ws
    - --ws.addr=0.0.0.0
    - --ws.port=8546
    - --ws.origins=*
    - --ws.api=admin,debug,eth,txpool,net,engine,web3,golembase,txpool
    - --syncmode=snap
    - --authrpc.vhosts=*
    - --authrpc.addr=0.0.0.0
    - --authrpc.port=8551
    - --authrpc.jwtsecret=/jwt/jwt
    - --usb=false
    - --state.scheme=hash
    - --nat=none
    - --bootnodes=enode://c8f046f0ea89e7b1f416048725489a6861daabff08d7b3e3a4bddcbd7d43799c9b2d7eb848e637937e862bbbdb4d675f6d9ef41a8f3c36c33dc9d2b8a10db148@195.201.165.105:30012,enode://42a8491f90b5388e21ad804b89edc196a4e3aac86b2b0f8337730cba0c43f5752943ca640bd4ae846d577276e4ce528eca3abfc938dec4299a9550b23c23f58c@195.201.165.105:30014,enode://5fd7fd9317d265ebb0e2d0e8c4dae4847d2331f7cd2dafb98a41cdd01aad0577678d0553209dc1d544da4b9b14225366906dcec016956a1136e86353200aa7cf@195.201.165.105:30016,enode://b36f8a3f5498247d916067e6e3e02103e0dd5b0f40adf7b3540c218cceddb0abf16d27545848488cd27f75f47bd8d9088f644079fcf2e757f99ff3a7d05a7c35@195.201.165.105:30018,enode://e543973b9a79be92760dee6c5bca06e333243c21b60126255a1e2c6cfbfb8f5faa0ace97ec548194297d3731fc873657d71e3cf48b6ea4d4ecb880e2f13edb5e@195.201.165.105:30020
    - --txpool.disable.non.golembase.transactions=true
    ports:
    - 8545:8545
    - 8546:8546
    volumes:
    - op_geth_data:/geth
    - jwt_shared:/jwt
  op-node:
    image: golemnetwork/golembase-l3-op-node:v1.13.4-holesky-t4-ff6ed28d
    restart: unless-stopped
    stop_grace_period: 5m
    depends_on:
      op-init:
        condition: service_completed_successfully
      op-geth:
        condition: service_started
    command:
    - op-node
    - --l1=https://l2.holesky.golem-base.io/rpc
    - --l1.beacon.ignore=true
    - --l1.rpckind=standard
    - --l1.trustrpc
    - --l2=http://op-geth:8551
    - --l2.enginekind=geth
    - --l2.jwt-secret=/jwt/jwt
    - --rpc.addr=0.0.0.0
    - --rpc.port=9545
    - --p2p.nat=true
    - --p2p.ban.peers=false
    - --p2p.bootnodes=enr:-J64QH_UOm3lsDElZuleIZBb2zVrfYFGv3jhfuw9HKZekNBSVJ4Zgm3y-miz9P7ixBcecvrtQK2yCjnywVKXuec0Sb6GAZl2ZzMFgmlkgnY0gmlwhMPJpWmHb3BzdGFja4SjnAEAiXNlY3AyNTZrMaEC1wg34dIkiO1s3Ab5sZNtuQyy-X_1XMjy3mAfdWH6onODdGNwgnU9g3VkcIJ1PQ,enr:-J64QJc_4QHL3eyuFTD-SeT_HJM1b-ohTWbEquT-rLrfEQbyRvStqTCOS_yRqmukGPnVOSaXuNciN0IBHhjQ-ppLQf6GAZl2ZytfgmlkgnY0gmlwhMPJpWmHb3BzdGFja4SjnAEAiXNlY3AyNTZrMaECCtcnj7S7GclQ6mNuPbdtXUo9cJ2kUtgmdeanbuYQ0u6DdGNwgnU_g3VkcIJ1Pw,enr:-J64QAmTfQOv_Rbks_IH9QVHG-Nqjss8WdA4nlioNY1SiSt-Q-Qakq2b511clKTSamfJrvT0iSIIrZeCg3fR-xZeZbGGAZl2ZytcgmlkgnY0gmlwhMPJpWmHb3BzdGFja4SjnAEAiXNlY3AyNTZrMaECLFt6D7uqXjdFfWA5eim1JVQ3sH3Gv7w_1Z2bom_Ci9eDdGNwgnVBg3VkcIJ1QQ,enr:-J64QGUQ9Fp_WU1g3oayk6LfP-XPUuVuEYiQk_dJC-S1tVfGKvh-bb3PxUcnbbqJLnmcfqmp6hlkhxNvkYD0HmLBM8WGAZl2ZytpgmlkgnY0gmlwhMPJpWmHb3BzdGFja4SjnAEAiXNlY3AyNTZrMaEC6vXqcRGO94Ibj96J06WiUCdwVkBl34kaXaRACcSZuH-DdGNwgnVDg3VkcIJ1Qw,enr:-J64QGEerEPzU0p86GsurY5jhW4SC-0kmr94LZw8nRRIHnuEcKmDlw0_B8Wr57GaZOLszEqrvywRoT2MAk2R1HKNzJyGAZl2ZytxgmlkgnY0gmlwhMPJpWmHb3BzdGFja4SjnAEAiXNlY3AyNTZrMaED6Ja7NpComZFaOkb4uvrZGJgBWU7mJFM5qpsFWR5XcFmDdGNwgnVFg3VkcIJ1RQ
    - --p2p.listen.tcp=9222
    - --p2p.listen.udp=9222
    - --metrics.enabled
    - --metrics.addr=0.0.0.0
    - --metrics.port=7300
    - --syncmode=execution-layer
    - --rollup.config=/rollup.json
    - --log.level=info
    ports:
    - 9545:9545
    volumes:
    - jwt_shared:/jwt
    - op_node_data:/op-node
