volumes:
    op_geth_data:
    op_node_data:
    jwt_shared:
services:
    # ========================================
    # OPTIMISM NODE SERVICES
    # ========================================
    op-init:
        image: alpine:latest
        command:
            - sh
            - -c
            - |
              set -e

              # Create config directory
              mkdir -p /config

              # Generate JWT secret if it doesn't exist
              if [ ! -f '/jwt/jwt' ]; then
                echo 'Generating JWT secret'
                mkdir -p /jwt
                # Generate a 32-byte random hex string for JWT secret
                apk add --no-cache openssl
                openssl rand -hex 32 > /jwt/jwt
                chmod 666 /jwt/jwt
                echo 'JWT secret generated successfully'
              else
                echo 'JWT secret already exists, skipping generation'
              fi
        volumes:
            - op_node_data:/op-node
            - jwt_shared:/jwt
    op-geth-init:
        image: golemnetwork/golembase-l3-op-geth:v1.101511.0-0.2-holesky-altda2-43fa37f3
        depends_on:
            op-init:
                condition: service_completed_successfully
        entrypoint: []
        command:
            - /bin/sh
            - -c
            - |
              set -e
              if [ ! -f '/geth/geth' ]; then
                echo 'Initializing geth data directory with genesis block...'

                # Use genesis file from op-init
                if ! geth init --state.scheme=hash --datadir='/geth' '/genesis.json'; then
                  echo 'ERROR: Failed to initialize geth with genesis block'
                  exit 1
                fi
                echo 'Geth initialized successfully with genesis block'
              else
                echo 'Geth data directory already initialized, skipping initialization'
              fi
        volumes:
            - op_geth_data:/geth
    op-geth:
        image: golemnetwork/golembase-l3-op-geth:v1.101511.0-0.2-holesky-altda2-43fa37f3
        restart: unless-stopped
        stop_grace_period: 5m
        depends_on:
            op-geth-init:
                condition: service_completed_successfully
        command:
            - --networkid=7
            - --datadir=/geth
            - --http
            - --http.corsdomain=*
            - --http.vhosts=*
            - --http.addr=0.0.0.0
            - --http.port=8545
            - --http.api=admin,debug,eth,txpool,net,engine,web3,golembase,txpool
            - --ws
            - --ws.addr=0.0.0.0
            - --ws.port=8546
            - --ws.origins=*
            - --ws.api=admin,debug,eth,txpool,net,engine,web3,golembase,txpool
            - --syncmode=snap
            - --authrpc.vhosts=*
            - --authrpc.addr=0.0.0.0
            - --authrpc.port=8551
            - --authrpc.jwtsecret=/jwt/jwt
            - --usb=false
            - --state.scheme=hash
            - --nat=none
            - --bootnodes=enode://9d3384b08c3950bc9c05f3048f3fbbbf3602559ce4ac02c7bc08c7fc616fd8907f5aefc51d13f561122bca9f08e71733f761a9659dd810bee7bbdf0d8f2cddc2@91.99.184.248:30012,enode://e1d7aae7e5d5ddaafb7088fc4f66af0fabeb28eec2c0a0f6b863946d26437d585c29127b42acb63eb2c125e18dc57390d67ec8e677cb136d8b95ee9d99043b78@91.99.157.203:30014,enode://fdf09555b3537f4d44bfff4bf23ee4cdd244b5ab236cd75d17eaa8884a83812dd5fe8e91b697b39eadb11a0ea44ad7c65ddaf2a0ff1ecbb79c8cfd545317e351@91.99.157.203:30016,enode://d0e9fb18e3fc4e791da6129d0d127e3c6f6b8562796acae985f81cf199e67caf8be94560b653cab5f70f45e89a3a8acf629ccc5c2a935c1df8f6d7318016f236@49.13.30.29:30018,enode://c57263663cafc750c07ed569ea94fa6c4f026dee4aac78d0de118b7858c2cc424cf5f4377e4840ba4f81817a1edb5fd515230f612f55f5d5fb7e9e7aee82f205@91.99.94.10:30020
            - --txpool.disable.non.golembase.transactions=true
        ports:
            - 8545:8545
            - 8546:8546
        volumes:
            - op_geth_data:/geth
            - jwt_shared:/jwt
    op-node:
        image: golemnetwork/golembase-l3-op-node:v1.13.0-holesky-altda2-5db4c285
        restart: unless-stopped
        stop_grace_period: 5m
        depends_on:
            op-init:
                condition: service_completed_successfully
            op-geth:
                condition: service_started
        command:
            - op-node
            - --l1=https://rpc.l2.holesky.golem-base.io
            - --l1.beacon.ignore=true
            - --l1.rpckind=standard
            - --l1.trustrpc
            - --l2=http://op-geth:8551
            - --l2.enginekind=geth
            - --l2.jwt-secret=/jwt/jwt
            - --rpc.addr=0.0.0.0
            - --rpc.port=9545
            - --p2p.nat=true
            - --p2p.ban.peers=false
            - --p2p.bootnodes=enr:-Jy4QPWAH0B7OZSD9yarxMQDcZVQThUpEP918MRioaw3ywGIXEeW0EmQq5fKHSofCO1BClilfb3JC9bf3KwRiB8RHLeGAZfumftqgmlkgnY0gmlwhFtjuPiHb3BzdGFja4IHAIlzZWNwMjU2azGhAjDjfZXovE-7hEujkBkUzXUP1-7X-uu0exRUKoe5il3ng3RjcIJ1PYN1ZHCCdT0,enr:-Jy4QAwZ2X-yXJXgHKZNbeGrwt9BhIlPutNDexYLr1LPXB3STgumzvtzdcPWr1BaC5ILPlhCWFQeRr1q2pUTSsMIA2OGAZfumf4LgmlkgnY0gmlwhFtjncuHb3BzdGFja4IHAIlzZWNwMjU2azGhAl6I6V5XOizMyvQc6F8Bnr_OAlGbXUIi11Wb_XyCzoDjg3RjcIJ1P4N1ZHCCdT8,enr:-Jy4QFjelvV8BbaCACIWiunZ1dlmUQIYip0SLx8tNBzG8HxSeExSmcYDOqTB7rCcPqzQQcLy0EFOWn9veBzXbwicKC2GAZfumf32gmlkgnY0gmlwhFtjncuHb3BzdGFja4IHAIlzZWNwMjU2azGhA3NiOjNEKvWHUt9gkYgYKEzTA3srrGX0bjovUN2e5qSag3RjcIJ1QYN1ZHCCdUE,enr:-Jy4QDOhNiuKvf2cHPZHw1gnDBMxYSlgUjSI-U6WQsF_wUMDea5HbyHJMt3vM5nKEmAoJ6nZCGB719AtlUMtsf2LKRSGAZfumfm0gmlkgnY0gmlwhDENHh2Hb3BzdGFja4IHAIlzZWNwMjU2azGhAwS6PUk9bjGYcRQd9Tp-_1asSpIIwu5_7z2UyV3X2qBng3RjcIJ1Q4N1ZHCCdUM,enr:-Jy4QP2HRBHxoxwRdlI-O7MnXvVpA-HmBNQV--M-TVWEP7viQDOoNfo1I2_UfDHrTyELAew37UZqGionEKrUXwFLVLmGAZfumf4qgmlkgnY0gmlwhFtjXgqHb3BzdGFja4IHAIlzZWNwMjU2azGhAjbsmdMJ3F3Sz3guG_Sd2Ahv0JzdFs9HDmatM50MgZ_ng3RjcIJ1RYN1ZHCCdUU
            - --p2p.listen.tcp=9222
            - --p2p.listen.udp=9222
            - --metrics.enabled
            - --metrics.addr=0.0.0.0
            - --metrics.port=7300
            - --syncmode=execution-layer
            - --rollup.config=/rollup.json
            - --log.level=info
        ports:
            - 9545:9545
        volumes:
            - jwt_shared:/jwt
            - op_node_data:/op-node
